// Copyright 2026 Sonar 3D-15 ROS Driver contributors
//
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file or at
// https://opensource.org/licenses/MIT.
// SPDX-License-Identifier: MIT

#include <gtest/gtest.h>

#include <cstdint>
#include <sstream>
#include <string>
#include <variant>
#include <vector>

#include "sonar3d/protocol.hpp"

namespace
{

sonar3d::protocol::RangeImage test_range_image()
{
  sonar3d::protocol::RangeImage image;
  image.header.timestamp = sonar3d::protocol::Timestamp{1007, 42};
  image.header.sequence_id = 7;
  image.width = 2;
  image.height = 1;
  image.horizontal_fov_degrees = 20.0F;
  image.vertical_fov_degrees = 10.0F;
  image.pixel_scale = 0.01F;
  image.pixels = {100, 200};
  return image;
}

std::vector<std::uint8_t> from_hex(const std::string & hex)
{
  std::vector<std::uint8_t> result;
  result.reserve(hex.size() / 2U);
  for (std::size_t index = 0; index < hex.size(); index += 2U) {
    result.push_back(static_cast<std::uint8_t>(std::stoul(hex.substr(index, 2), nullptr, 16)));
  }
  return result;
}

TEST(Protocol, DecodesOfficialWlsonarRip1Packet)
{
  // Generated by wlsonar v0.5.4's packb from a known RangeImage. Keeping an
  // external golden packet prevents a self-consistent encoder/decoder bug
  // from masquerading as wire compatibility.
  const auto packet = from_hex(
    "524950316c0000000a5e0a39747970652e676f6f676c65617069732e636f6d2f"
    "77617465726c696e6b65642e736f6e61722e70726f746f636f6c2e52616e6765"
    "496d61676512210a070a0308ef071007280230013d0000a04145000020414d0ad7"
    "233c520364c8016ba0c81c");

  const auto decoded = sonar3d::protocol::decode_packet(packet);

  ASSERT_EQ(decoded.version, sonar3d::protocol::ProtocolVersion::RIP1);
  ASSERT_TRUE(std::holds_alternative<sonar3d::protocol::RangeImage>(decoded.message));
  const auto & image = std::get<sonar3d::protocol::RangeImage>(decoded.message);
  EXPECT_EQ(image.header.sequence_id, 7U);
  ASSERT_TRUE(image.header.timestamp);
  EXPECT_EQ(image.header.timestamp->seconds, 1007);
  EXPECT_EQ(image.width, 2U);
  EXPECT_EQ(image.height, 1U);
  EXPECT_FLOAT_EQ(image.pixel_scale, 0.01F);
  EXPECT_EQ(image.pixels, (std::vector<std::uint32_t>{100, 200}));
}

TEST(Protocol, RoundTripsRip1AndRip2)
{
  const sonar3d::protocol::Message source = test_range_image();
  for (const auto version : {
      sonar3d::protocol::ProtocolVersion::RIP1,
      sonar3d::protocol::ProtocolVersion::RIP2})
  {
    const auto encoded = sonar3d::protocol::encode_packet(source, version);
    const auto decoded = sonar3d::protocol::decode_packet(encoded);

    EXPECT_EQ(decoded.version, version);
    ASSERT_TRUE(std::holds_alternative<sonar3d::protocol::RangeImage>(decoded.message));
    EXPECT_EQ(std::get<sonar3d::protocol::RangeImage>(decoded.message), test_range_image());
  }
}

TEST(Protocol, RoundTripsBitmapAndImuMessages)
{
  sonar3d::protocol::BitmapImage bitmap;
  bitmap.header.sequence_id = 8;
  bitmap.type = sonar3d::protocol::BitmapImageType::SHADED_IMAGE;
  bitmap.width = 2;
  bitmap.height = 2;
  bitmap.pixels = {0, 1, 254, 255};

  auto decoded = sonar3d::protocol::decode_packet(
    sonar3d::protocol::encode_packet(bitmap, sonar3d::protocol::ProtocolVersion::RIP2));
  ASSERT_TRUE(std::holds_alternative<sonar3d::protocol::BitmapImage>(decoded.message));
  EXPECT_EQ(std::get<sonar3d::protocol::BitmapImage>(decoded.message), bitmap);

  sonar3d::protocol::ImuBatch imu;
  imu.sequence_id = 9;
  imu.sample_count = 1;
  imu.timestamps = {{10, 20}};
  imu.specific_force = {1.0F, 2.0F, 3.0F};
  imu.rate_of_turn = {4.0F, 5.0F, 6.0F};
  decoded = sonar3d::protocol::decode_packet(
    sonar3d::protocol::encode_packet(imu, sonar3d::protocol::ProtocolVersion::RIP1));
  ASSERT_TRUE(std::holds_alternative<sonar3d::protocol::ImuBatch>(decoded.message));
  EXPECT_EQ(std::get<sonar3d::protocol::ImuBatch>(decoded.message), imu);
}

TEST(Protocol, RejectsBadFramingAndCrc)
{
  auto encoded = sonar3d::protocol::encode_packet(test_range_image());

  auto bad_identifier = encoded;
  bad_identifier[0] = 'X';
  try {
    static_cast<void>(sonar3d::protocol::decode_packet(bad_identifier));
    FAIL() << "expected bad identifier";
  } catch (const sonar3d::protocol::ProtocolError & error) {
    EXPECT_EQ(error.code(), sonar3d::protocol::ErrorCode::BAD_IDENTIFIER);
    EXPECT_FALSE(error.framing_intact());
  }

  auto bad_crc = encoded;
  bad_crc[bad_crc.size() - 1U] ^= 0x01U;
  try {
    static_cast<void>(sonar3d::protocol::decode_packet(bad_crc));
    FAIL() << "expected CRC mismatch";
  } catch (const sonar3d::protocol::ProtocolError & error) {
    EXPECT_EQ(error.code(), sonar3d::protocol::ErrorCode::CRC_MISMATCH);
    EXPECT_TRUE(error.framing_intact());
  }

  encoded.push_back(0);
  EXPECT_THROW(
    static_cast<void>(sonar3d::protocol::decode_packet(encoded)),
    sonar3d::protocol::ProtocolError);
}

TEST(Protocol, ReadsMixedRecordingAndDetectsTruncation)
{
  const auto rip1 = sonar3d::protocol::encode_packet(
    test_range_image(), sonar3d::protocol::ProtocolVersion::RIP1);
  const auto rip2 = sonar3d::protocol::encode_packet(
    test_range_image(), sonar3d::protocol::ProtocolVersion::RIP2);
  std::string bytes(rip1.begin(), rip1.end());
  bytes.append(rip2.begin(), rip2.end());
  std::istringstream stream(bytes);

  ASSERT_TRUE(sonar3d::protocol::read_packet(stream));
  ASSERT_TRUE(sonar3d::protocol::read_packet(stream));
  EXPECT_FALSE(sonar3d::protocol::read_packet(stream));

  std::istringstream truncated(bytes.substr(0, bytes.size() - 1U));
  ASSERT_TRUE(sonar3d::protocol::read_packet(truncated));
  EXPECT_THROW(
    static_cast<void>(sonar3d::protocol::read_packet(truncated)),
    sonar3d::protocol::ProtocolError);
}

}  // namespace
